# Generated by Django 5.2.8 on 2025-12-04 06:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('product_type', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software')], default='hardware', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_categories',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['product_type', 'is_active'], name='product_cat_product_3a500c_idx'), models.Index(fields=['slug'], name='product_cat_slug_801f9e_idx')],
            },
        ),
    ]
