# Generated by Django 5.2.8 on 2025-12-04 08:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDescription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Product Subcategory Description',
                'verbose_name_plural': 'Product Subcategory Descriptions',
                'db_table': 'product_subcategory_descriptions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=510, null=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug', max_length=510, unique=True)),
                ('series', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('msrp', models.DecimalField(decimal_places=2, help_text='Main Price', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price after discount', max_digits=10)),
                ('stock', models.IntegerField(default=100)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('mfr_part', models.CharField(blank=True, help_text='Manufacturer Part Number', max_length=255, null=True)),
                ('shi_part', models.CharField(blank=True, help_text='Shipper Part Number', max_length=255, null=True)),
                ('unspsc', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(help_text='Full product description (comma-separated for overview)')),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying subcategories')),
            ],
            options={
                'verbose_name': 'Product Subcategory',
                'verbose_name_plural': 'Product Subcategories',
                'db_table': 'product_subcategories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.RenameIndex(
            model_name='productcategory',
            new_name='product_pro_product_c7c576_idx',
            old_name='product_cat_product_3a500c_idx',
        ),
        migrations.RenameIndex(
            model_name='productcategory',
            new_name='product_pro_slug_9fef6f_idx',
            old_name='product_cat_slug_801f9e_idx',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for displaying categories'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table=None,
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productsubcategory'),
        ),
        migrations.AddField(
            model_name='categorydescription',
            name='productSubCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productsubcategory'),
        ),
        migrations.AddIndex(
            model_name='productsubcategory',
            index=models.Index(fields=['category', 'is_active'], name='product_sub_categor_061d15_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubcategory',
            index=models.Index(fields=['slug'], name='product_sub_slug_27dcc8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory', 'is_active'], name='products_subcate_218b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['manufacturer', 'is_active'], name='products_manufac_b93a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='products_created_a77fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_slug_5e91f2_idx'),
        ),
    ]
