# Generated by Django 5.2.8 on 2025-12-04 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_categorydescription_product_productsubcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this description block active?')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Product Description',
                'verbose_name_plural': 'Product Descriptions',
                'db_table': 'product_descriptions',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductDescriptionRow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productdescription')),
            ],
            options={
                'verbose_name': 'Product Description Row',
                'verbose_name_plural': 'Product Description Rows',
                'db_table': 'product_description_rows',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='productdescription',
            index=models.Index(fields=['product', 'is_active'], name='product_des_product_8bc96e_idx'),
        ),
        migrations.AddIndex(
            model_name='productdescription',
            index=models.Index(fields=['display_order'], name='product_des_display_08b584_idx'),
        ),
        migrations.AddIndex(
            model_name='productdescriptionrow',
            index=models.Index(fields=['description', 'display_order'], name='product_des_descrip_38f173_idx'),
        ),
    ]
