# Generated by Django 5.2.8 on 2025-12-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productcategory_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productcategory',
            name='product_pro_product_c7c576_idx',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software')], default='hardware', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'is_active'], name='products_product_6ea65b_idx'),
        ),
    ]
