# Generated by Django 5.2.8 on 2025-12-06 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsubcategory', to='product.productcategory'),
        ),
    ]
