# Generated by Django 5.2.8 on 2025-12-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productsubcategory_category'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_product_6ea65b_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product_type',
            field=models.CharField(blank=True, choices=[('hardware', 'Hardware'), ('software', 'Software')], default='hardware', max_length=255, null=True),
        ),
    ]
