# Generated by Django 5.2.8 on 2025-12-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='title',
        ),
    ]
