# Generated by Django 5.2.8 on 2025-12-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_productreview_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
