# Generated by Django 5.2.8 on 2025-11-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='auth_provider',
            field=models.CharField(blank=True),
        ),
    ]
