# Generated by Django 5.2.8 on 2025-11-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_users_auth_provider_alter_users_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='otp_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
