# Generated by Django 5.2.8 on 2026-02-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_requestquote_contantinfo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestquote',
            name='interest',
            field=models.CharField(max_length=1000),
        ),
    ]
