# Generated by Django 5.2.8 on 2025-12-13 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_type',
            new_name='pricuct_type',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='prodtity',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='quane',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
