# Generated by Django 5.2.8 on 2025-12-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_product_type_orderitem_pricuct_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quane',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='pricuct_type',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='prodtity',
            new_name='quantity',
        ),
    ]
