# Generated by Django 5.2.8 on 2025-12-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_quane_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
