# Generated by Django 5.2.8 on 2025-12-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_users_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='auth_provider',
        ),
    ]
