# Generated by Django 5.2.8 on 2025-12-23 04:52

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_users_options_alter_users_otp_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', authentication.models.CustomUserManager()),
            ],
        ),
    ]
